<zero-to-five> ::= '0' | '1' | '2' | '3' | '4' | '5'
<six-to-nine> ::= '6' | '7' | '8' | '9'

<digit> ::= <zero-to-five> | <six-to-nine>

<watch-digits> ::= <zero-to-five><digit>
<base-sixty> ::= <watch-digits> | <digit>


<integer> ::=
| <digit>
| <digit><integer>

<decimal-separator> ::= ',' | '.'

<decimal> ::=
| <integer><decimal-separator><digit>
| <integer>

<distance> ::= <integer>'m' | <decimal>'km'

<time> ::=
| <integer>':'<watch-digits>':'<watch-digits>
| <base-sixty>':'<watch-digits>
| <base-sixty>'min'
| <base-sixty>'s'
| <base-sixty>'min'<base-sixty>'s'
| <integer>'h'<base-sixty>'min'<base-sixty>'s'
| <integer>'h'<base-sixty>'min'
| <integer>'h'<base-sixty>'s'


<pace> ::=
| <integer>':'<base-sixty>'/km'
| 'CL'
| 'CA'
| 'CV'
| 'TR'
| 'LVS'
| 'LE'
| 'MO'
| 'FO'
| 'FTS'
| 'MAX'

<progression> ::= <pace>'~'<pace>

<plus> ::= '+' | '/'

<times> ::= 'x'

<interval> ::=
| <time> <distance>
| <time> <pace>
| <distance> <pace>
| <distance> <progression>

<repetition> :: =
| <interval>
| <integer><times> '('<workout>')'

<workout> :: =  <repetition>*
