<zero-to-five> ::= '0' | '1' | '2' | '3' | '4' | '5'
<six-to-nine> ::= '6' | '7' | '8' | '9'

<digit> ::= <zero-to-five> | <six-to-nine>

<base-sixty> ::= <zero-to-five><digit>

<integer> ::=
| <digit>
| <digit><integer>

<decimal> ::=
| <integer>'.'<digit>
| <integer>

<time> ::=
| <integer>':'<base-sixty>':'<base-sixty>
| <integer>':'<base-sixty>
| <integer>'min'
| <integer>'s'
| <integer>'min' <integer>'s'
| <integer>'h' <integer>'min' <integer>'s'
| <integer>'h' <integer>'min'

<distance> ::= <integer>'m' | <decimal>'km'

<pace> ::=
| <integer>':'<base-sixty>'/km'
| 'CL'
| 'CA'
| 'CV'
| 'TR'
| 'LVS'
| 'LE'
| 'MO'
| 'FO'
| 'FTS'
| 'MAX'

<progression> ::= <pace>'~'<pace>

<plus> ::= '+' | '/'

<times> ::= 'x'

<interval> ::=
| <time> <pace>
| <distance> <pace>
| <distance> <progression>

<repetition> :: =
| <interval>
| <repetition> <plus> <repetition>
| <integer><times> '('<repetition>')'
